import {NgModule} from '@angular/core';

import {
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatLineModule,
    MatListModule,
    MatMenuModule,
    MatOptionModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatToolbarModule,
    MatTableModule,
    MatPaginatorModule,
    MatTabsModule,
    MatTreeModule
} from "@angular/material";
import {CommonModule} from "@angular/common";

@NgModule({
    declarations: [
    ],
    imports: [
        CommonModule,
        MatInputModule,
        MatFormFieldModule,
        MatListModule,
        MatSidenavModule,
        MatToolbarModule,
        MatButtonModule,
        MatDialogModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatSelectModule,
        MatSliderModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatCheckboxModule,
        MatCardModule,
        MatIconModule,
        MatDatepickerModule,
        MatDividerModule,
        MatStepperModule,
        MatSortModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatOptionModule,
        MatMenuModule,
        MatLineModule,
        MatRadioModule,
        MatRippleModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatTableModule,
        MatPaginatorModule,
        MatTabsModule,
        MatTreeModule
    ],
    exports: [
        MatFormFieldModule,
        MatInputModule,
        MatListModule,
        MatToolbarModule,
        MatSidenavModule,
        MatButtonModule,
        MatDialogModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatSelectModule,
        MatSliderModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatCheckboxModule,
        MatCardModule,
        MatIconModule,
        MatDatepickerModule,
        MatDividerModule,
        MatStepperModule,
        MatSortModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatOptionModule,
        MatMenuModule,
        MatLineModule,
        MatRadioModule,
        MatRippleModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatTableModule,
        MatPaginatorModule,
        MatTabsModule,
        MatTreeModule
    ],
    providers: [
    ],
    bootstrap: []
})
export class MaterialModule {
}
